spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8081
